[package]
name = "gpa-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.3"
serde_json = "1.0.104"
rand = "0.8.5"
chrono = "0.4.26"
infer = "0.15.0"
dotenvy = "0.15.7"
thiserror = "1.0.44"
